/* This file is automatically generated by gitinfo_headgen.sh.
 * Do not edit this file directly.
 */

#ifndef GITINFO_H
#define GITINFO_H

#define GIT_VERSION "main@a2006bd"

#define GIT_HASH "a2006bd"
#define GIT_BRANCH "main"
#define GIT_TAG ""

#endif

