#define APPLICATION_NAME "Coffeekitty"
#define APPLICATION_DESCRIPTION "A terminal-based management tool for collective coffee spending"
#define APPLICATION_VERSION "Dev"
#define COPYRIGHT "Copyright (C) 2025 Alexander Hahn (https://github.com/hahnworks)"
#define LICENSE "This program is free software: you can redistribute it and/or modify it under the terms of the European Union Public License (EUPL), version 1.2."