/*
 * This file is part of Coffeekitty.
 * 
 * Copyright (C) 2025 Alexander Hahn
 * 
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the European Union Public License (EUPL), version 1.2.
 * 
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
 * European Union Public License for more details.
 * 
 * You should have received a copy of the European Union Public License
 * along with this program. If not, see <https://joinup.ec.europa.eu/collection/eupl/eupl-text-eupl-12>.
 */

#include "latex.h"

#include <stdio.h>
#include <stdlib.h>
#include <string.h>

#include "kitty.h"
#include "currency.h"
#include "metainfo.h"

const char* LATEX_PREAMBLE =
"\\documentclass[landscape]{article}\n"
"\\usepackage[a4paper, margin=1in]{geometry}\n"
"\\usepackage{pdflscape}\n"
"\\usepackage{tabularx}\n"
"\\usepackage{color}\n"
"\\usepackage{fancyhdr}\n"
"\n"
"\\begin{document}\n"
"\t\\renewcommand{\\arrayrulewidth}{.5pt}\n"
"\t\\pagestyle{fancy}\n"
"\t\\renewcommand{\\headrulewidth}{0pt}\n"
"\t\\fancyhf{}\n";

const char* LATEX_EPILOG =
"\\end{document}\n";

const char* T1 = "\t";
const char* T2 = "\t\t";
const char* T3 = "\t\t\t";

const int MIN_ROW_HEIGHT_IN_HPT = 25;
const int MAX_TOTAL_ROW_HEIGHT_IN_HPT = 250;
const int ARRAY_RULE_WIDTH_IN_HPT = 1;

// measurement is done in half pt
// every table base requires 1 hpt
// every person requires an additional 1 hpt (line) and has a minimum cell height of 25 hpt
// the total distributable height is 640 + 1 hpt

void fprint_latex_kitty_properties(FILE* file, const Kitty *kitty, const char* prefix)
{
    fprintf(file, "%s\\begin{tabular}{l  l  l}\n", prefix);
    fprintf(file, "%s%sTotal Balance: & %s & + %i Packs\\\\\n", prefix, T1, currency_value_format(kitty->balance, false, true), kitty->packs);
    fprintf(file, "%s%sCounter: & %d & \\\\\n", prefix, T1, kitty->counter);
    fprintf(file, "%s%sPrice: & %s/Coffee & \\\\\n", prefix, T1, currency_value_format(kitty->price, false, true));
    fprintf(file, "%s%sLast Settlement: & & \\\\\n", prefix, T1);
    fprintf(file, "%s\\end{tabular}\n", prefix);
}

void fprint_latex_tallytabular(FILE* file, const Kitty *kitty, bool skeleton, const char* prefix){
    fprintf(file, "%s\\begin{tabularx}{\\textwidth}{|l|r|X|p{3cm}|}\n", prefix);
    fprintf(file, "%s\t\\hline\n", prefix);
    fprintf(file, "%s\t\\textbf{Name} & \\textbf{Balance}/%s & & \\textbf{Expenses} \\\\\n", prefix, kitty->settings->currency->isoname);
    fprintf(file, "%s\t\\hline\n", prefix);

    for (Person* p = kitty->persons; p != NULL; p = p->next) {
        fprintf(file, "%s\t\\hline\n", prefix);

        char balance_color_modifier[128] = "{";
        char balance_boldness_modifier[128] = "{";
        if (p->balance->value < 0) {
            snprintf(balance_color_modifier, sizeof(balance_color_modifier), "\\textcolor{red}{");
            if (p->balance->value < -10000) {
                snprintf(balance_boldness_modifier, sizeof(balance_boldness_modifier), "\\textbf{");
            }
        }

        fprintf(file, "%s%s & %s%s%s%s%s &  &  \\\\",
            T3, p->name,
            balance_color_modifier, balance_boldness_modifier,
            currency_value_format(p->balance, false, false),
            "}","}"
            );
        if (!skeleton)
            fprintf(file, "[%f\\distributablespace]",
                p->thirst);
        fprintf(file, "\n");
    }
    fprintf(file, "%s\t\\hline\n%s\\end{tabularx}\n", prefix, prefix);
}

int fprint_new_latex_sheet(FILE* file, const Kitty *kitty)
{
    fprintf(file, "%s", LATEX_PREAMBLE);
    fprintf(file, "\t\\fancyhead[C]{\\textbf{%s}}\n", "Coffee Fund");
    fprintf(file, "\t\\fancyfoot[R]{\\footnotesize Generated by %s v%s}\n", APPLICATION_NAME, APPLICATION_VERSION);

    fprintf(file, "\t\\newsavebox{\\overviewtablebox}\n");
    fprintf(file, "\t\\sbox{\\overviewtablebox}{\n");
    fprint_latex_kitty_properties(file, kitty, T1);
    fprintf(file, "\t}\n");

    fprintf(file, "\t\\renewcommand{\\arraystretch}{1.5}\n");
    fprintf(file, "\t\\newsavebox{\\skeletontablebox}\n");
    fprintf(file, "\t\\sbox{\\skeletontablebox}{\n");
    fprint_latex_tallytabular(file, kitty, true, T2);
    fprintf(file, "\t}\n");

    fprintf(file, "\t\\newlength{\\overviewtableheight}\n");
    fprintf(file, "\t\\setlength{\\overviewtableheight}{\\dimexpr\\ht\\overviewtablebox + \\dp\\overviewtablebox\\relax}\n");
    fprintf(file, "\t\\newlength{\\skeletontableheight}\n");
    fprintf(file, "\t\\setlength{\\skeletontableheight}{\\dimexpr\\ht\\skeletontablebox + \\dp\\skeletontablebox\\relax}\n");
    fprintf(file, "\t\\newlength{\\distributablespace}\n");
    fprintf(file, "\t\\setlength{\\distributablespace}{\\dimexpr(\\textheight - \\overviewtableheight - \\skeletontableheight - \\baselineskip)}\n");

    // OVERVIEW
    fprintf(file, "\t\\usebox{\\overviewtablebox} \\\\\n");

    fprintf(file, "\t\\vspace{\\baselineskip} \\\\ \n");

    // TABLE
    fprint_latex_tallytabular(file, kitty, false, T2);

    fprintf(file, "%s", LATEX_EPILOG);
    return 0;
}